### ISSUE TITLE
missing source files

### ISSUE THREAD

**Issue by pavel-demin** [VE3NEA/HamVNA#1]
Hi Alex,

First of all, many thanks for opening the HamVNA source code. Reading your code helped me a lot to understand how all the scattering parameters are calculated.

Now I'd like to compile the code but some .pas files seem to be missing. I see the following lines in [HamVNA.dpr](https://github.com/VE3NEA/HamVNA/blob/master/HamVNA.dpr)

```
  ComplMath in '..\..\VCL\Math\ComplMath.pas',
  AngleTxt in '..\..\VCL\AlCommon\AngleTxt.pas',
  SndTypes0 in '..\..\VCL\SND\SndTypes0.pas',
  LaPackWrap in '..\..\VCL\Math\LaPackWrap.pas',
  VectFitt in '..\..\VCL\Math\VectFitt.pas',
  UdpBrdCast in '..\..\VCL\AlNet\UdpBrdCast.pas',
  JwaIpTypes in '..\..\VCL3RD\Jwa\JwaIpTypes.pas';
```

Could you please explain me where to find these files?

Best regards,

Pavel

**Comment by VE3NEA** [comment]
Hi Pavel,

I have just added the missing files to the GitHub repository, they are in the Lib folder.

73 Alex VE3NEA

**Comment by pavel-demin** [comment]
Thanks for adding the missing files.
